use-configs:
  - lint/copyrights
lint:
  copyright:
    confidential_header:
      valids:
        - .*embargo.*
      file_types:
        bash:
          comment_end: ''
        bat:
          comment_begin: REM
          comment_end: ""
          comment_char: REM

  ults-needed:
    disabled: true

  binary_files:
    disabled: true
