name: CI

on:
  push:
    branches: [ master, test_ci ]
  pull_request:
    branches: [ master, test_ci ]

jobs:
  check_formatting:
    runs-on: [self-hosted, gfx, small]

    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        command: >
          scripts/run_clang-format_on_all_files.sh   &&
          echo "Checking diff after formatting..."   &&
          git diff --exit-code                       &&
          echo "OK"

  build_release:
    runs-on: [self-hosted, gfx, small]

    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        command: >
          mkdir build                                              &&
          cd build                                                 &&
          cmake ..                                                  \
            -DCMAKE_BUILD_TYPE=Release                              \
            -DGENERATE_DOCS=ON                                      \
            -DBUILD_HELLO_WORLD=ON                                  \
            -DBUILD_SINGLE_API_BINARIES=ON                          \
            -DBUILD_ALL_API_BINARIES=ON                             \
            -DLOG_BENCHMARK_TARGETS=ON                             &&
          echo "Compiling on `nproc` threads"                      &&
          make -j`nproc`                                           &&
          echo "Checking diff after generating documentation..."   &&
          git diff --exit-code                                     &&
          echo "OK"
