name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_release:
    runs-on: [self-hosted, gfx, small, fm6pusghr053] # TODO remove fm6pusghr053 after 2021-06-28

    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        command: >
          mkdir build                                              &&
          cd build                                                 &&
          cmake .. -DCMAKE_BUILD_TYPE=Release -DGENERATE_DOCS=ON   &&
          echo "Compiling on `nproc` threads"                      &&
          make -j`nproc`                                           &&
          echo "Checking diff after generating documentation..."   &&
          git diff --exit-code                                     &&
          echo "OK"
